### PR TITLE
bch: use Python's built-in json library

### PR DESCRIPTION
**Pull request by commodo**
Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
i've not tested this;

i just want to trigger a discussion that is similar to the one here https://github.com/hardwario/bch-gateway/pull/17  and   https://github.com/hardwario/bch-gateway/issues/16

**Comment by commodo** [comment]
since https://github.com/hardwario/bch-gateway/pull/17 was merged, then this is left here;

i will do some patches in OpenWrt, to patch Bigclown stuff to remove simplejson and then remove the package;

**Comment by commodo** [comment]
ping :)

**Comment by commodo** [comment]
ping again :)

**Review by blavka — APPROVED** [review]

**Comment by blavka** [comment]
I'm sorry, of course I'll take it.

**Comment by commodo** [comment]
No worries.
I was busy alternating with other projects as well.

**Comment by commodo** [comment]
> No worries. I was busy alternating with other projects as well.

And thank you :)

**Comment by blavka** [comment]
Release:
bch 1.2.0

**Pull request merged**
